import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import {
  assertSemver,
  assertVersionsConsistent,
  nextVersion,
  readVersions,
  setVersions,
} from "./version-utils.mjs";

const scriptDir = dirname(fileURLToPath(import.meta.url));

function tempProject() {
  const root = join(
    tmpdir(),
    `token-fire-version-${Date.now()}-${Math.random().toString(16).slice(2)}`,
  );
  mkdirSync(join(root, "src-tauri"), { recursive: true });
  writeFileSync(
    join(root, "package.json"),
    JSON.stringify({ name: "token-fire", version: "0.1.0" }, null, 2) + "\n",
  );
  writeFileSync(
    join(root, "src-tauri", "tauri.conf.json"),
    JSON.stringify({ productName: "TokenFire", version: "0.1.0" }, null, 2) + "\n",
  );
  writeFileSync(
    join(root, "src-tauri", "Cargo.toml"),
    `[package]\nname = "token-fire"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\nserde = "1"\n`,
  );
  writeFileSync(
    join(root, "src-tauri", "Cargo.lock"),
    `# This file is automatically @generated by Cargo.\n\n[[package]]\nname = "serde"\nversion = "1.0.0"\n\n[[package]]\nname = "token-fire"\nversion = "0.1.0"\ndependencies = [\n "serde",\n]\n`,
  );
  return root;
}

test("readVersions reads all release metadata files", () => {
  const root = tempProject();

  assert.deepEqual(readVersions(root), {
    packageJson: "0.1.0",
    cargoToml: "0.1.0",
    tauriConfig: "0.1.0",
    cargoLock: "0.1.0",
  });
});

test("assertVersionsConsistent returns the shared version", () => {
  assert.equal(
    assertVersionsConsistent({
      packageJson: "0.1.0",
      cargoToml: "0.1.0",
      tauriConfig: "0.1.0",
      cargoLock: "0.1.0",
    }),
    "0.1.0",
  );
});

test("bump-version CLI accepts pnpm-style argument separator", () => {
  const root = tempProject();
  const output = execFileSync(
    process.execPath,
    [join(scriptDir, "bump-version.mjs"), "--", "0.1.1"],
    {
      cwd: root,
      encoding: "utf8",
    },
  );

  assert.match(output, /TokenFire version updated: 0\.1\.0 -> 0\.1\.1/);
  assert.deepEqual(readVersions(root), {
    packageJson: "0.1.1",
    cargoToml: "0.1.1",
    tauriConfig: "0.1.1",
    cargoLock: "0.1.1",
  });
});

test("assertVersionsConsistent rejects drift", () => {
  assert.throws(
    () =>
      assertVersionsConsistent({
        packageJson: "0.1.0",
        cargoToml: "0.1.1",
        tauriConfig: "0.1.0",
        cargoLock: "0.1.0",
      }),
    /version drift/,
  );
});

test("assertSemver rejects non-SemVer release strings", () => {
  assert.throws(() => assertSemver("2026.07.08"), /SemVer/);
  assert.throws(() => assertSemver("0.1"), /SemVer/);
  assert.doesNotThrow(() => assertSemver("0.1.1"));
});

test("nextVersion computes patch, minor, and major bumps", () => {
  assert.equal(nextVersion("0.1.0", "patch"), "0.1.1");
  assert.equal(nextVersion("0.1.9", "minor"), "0.2.0");
  assert.equal(nextVersion("0.9.9", "major"), "1.0.0");
});

test("setVersions writes the same version to every metadata file", () => {
  const root = tempProject();

  setVersions(root, "0.1.1");

  assert.deepEqual(readVersions(root), {
    packageJson: "0.1.1",
    cargoToml: "0.1.1",
    tauriConfig: "0.1.1",
    cargoLock: "0.1.1",
  });
  assert.match(
    readFileSync(join(root, "src-tauri", "Cargo.toml"), "utf8"),
    /\[package\]\nname = "token-fire"\nversion = "0\.1\.1"/,
  );
  assert.match(
    readFileSync(join(root, "src-tauri", "Cargo.lock"), "utf8"),
    /\[\[package\]\]\nname = "token-fire"\nversion = "0\.1\.1"/,
  );
});

test("setVersions preserves JSON formatting outside the version field", () => {
  const root = tempProject();
  writeFileSync(
    join(root, "src-tauri", "tauri.conf.json"),
    `{
  "productName": "TokenFire",
  "version": "0.1.0",
  "bundle": {
    "targets": ["app", "dmg"]
  }
}
`,
  );

  setVersions(root, "0.1.1");

  assert.match(readFileSync(join(root, "src-tauri", "tauri.conf.json"), "utf8"), /"targets": \["app", "dmg"\]/);
});
